# Generated by Django 5.1.7 on 2025-03-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_album_view_delete_album_delete_albumset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_view',
            name='album_name',
            field=models.CharField(max_length=100),
        ),
    ]
