# Generated by Django 5.1.7 on 2025-03-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_model_category_name_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='categories',
            field=models.ManyToManyField(related_name='tasks', to='categories.category_model'),
        ),
    ]
