# Generated by Django 5.1.7 on 2025-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_model',
            name='Category_Name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category_model',
            name='task_model',
            field=models.ManyToManyField(blank=True, related_name='category', to='tasks.task_model'),
        ),
    ]
