# Generated by Django 5.1.7 on 2025-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(choices=[('Guitar', 'Guitar'), ('Piano', 'Piano'), ('Violin', 'Violin'), ('Drums', 'Drums'), ('Flute', 'Flute')], max_length=20),
        ),
    ]
