# Generated by Django 5.1.7 on 2025-03-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musician_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
